# -*- coding: utf-8 -*-
"""SHAI_ASSIG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQpO5JAva_-tLzYcYt40S0BFLsEFzqJO
"""

import pandas as pd
import numpy as np

# Load your dataset
df = pd.read_csv('/Salaries.csv')

#identify no. of rows and colmuns
rows,cols=df.shape
print(f"No. Of Rows in the dataset: {rows}")
print(f"No. Of columns in the dataset: {cols}")


#identify data types
data_types=df.dtypes
print(f"data types are : {data_types}")


#identify missing values
missing_values=df.isnull().sum()
print(f"no of missing values in each column : {missing_values} ")

"""Task 1

"""

# @title Default title text
import pandas as pd

df = pd.read_csv('/Salaries.csv')
salaries_info=df['TotalPay'].describe()
mod=df['TotalPay'].mode()
repeatition= df['TotalPay'].eq(mod.iloc[0]).sum()


print(f'mean of salaries: {salaries_info[1]}')
print(f'median of salaries: {salaries_info[5]}')
print(f'mode of salaries: {mod.iloc[0]}   |  repeated : {repeatition} times')
print(f'minimum  salary: {salaries_info[3]}')
print(f'maximum  salary: {salaries_info[7]}')
print(f'std of salaries: {salaries_info[2]}')
print(f'range of salaries: {salaries_info[3]} : {salaries_info[7]}')

# ----------------------data cleaning---------------------------------
import pandas as pd

df = pd.read_csv('/Salaries.csv')

#create a mask for salaries less 0 (remove outliers)
df = df[df['TotalPay'] > 0]
df.shape
df.to_csv('/Salaries.csv',index=False)
df.head()

#---------------------------------data vizualization (Histogram)---------------------------------
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('/Salaries.csv')
plt.hist(df['TotalPay'] ,bins=100, rwidth=0.9 ,color='r')
plt.xlabel('Salaries')
plt.ylabel('Frequency')
plt.title('TotalPay Histogram')

# Display the histogram
plt.show()

#---------------------------------data vizualization (Pie Chart)---------------------------------

import pandas as pd
import matplotlib.pyplot as plt

#load data
df=pd.read_csv('/Salaries.csv')


#extract departments

#df['Department']= ( '(' in df['JobTitle'] and ')' in df['JobTitle'] ? )

unknown_dept=df[df['JobTitle'].str.find('DEPARTMENT)')==-1]
unknown_dept['Department']='Unknown'
unknown_dept.head()

known_dept=df[df['JobTitle'].str.find('DEPARTMENT)')!=-1]
known_dept['Department']=df['JobTitle'].str.split('DEPARTMENT')[0].str.split('(')[1]
known_dept.head()

# ---------------------------------statistical comarison---------------------------------

import pandas as pd
import matplotlib.pyplot as plt

#load data
df=pd.read_csv('/Salaries.csv')

df_grouped=df.groupby('JobTitle')
df_grouped.head(10)

summary_statistics = df_grouped.agg({
    'TotalPayBenefits': ['mean', 'median', 'std', 'min', 'max', 'count']
})

# Comparing the average salaries across different groups
average_salaries_comparison = summary_statistics['TotalPayBenefits'][['mean', 'median', 'std']]

print(average_salaries_comparison)

# ---------------------------------correlation between salary and otherpay ---------------------------------

import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv('/Salaries.csv')

correlation_coefficient = data['TotalPayBenefits'].corr(data['OtherPay'])

# Plot scatter plot
plt.figure(figsize=(8, 6))
plt.scatter(data['OtherPay'], data['TotalPayBenefits'], alpha=0.5)
plt.title('Scatter Plot of TotalPayBenefits vs. OtherPay')
plt.xlabel('OtherPay')
plt.ylabel('TotalPayBenefits')
plt.grid(True)
plt.show()

print("Correlation coefficient between salary and numerical column:", correlation_coefficient)